class LanguageLocal {
  final isoLangs = {
    "ab": {"name": "Abkhaz", "nativeName": "аҧсуа"},
    "ace": {"name": "Achinese", "nativeName": "Acèh"},
    "ach": {"name": "Acoli", "nativeName": "Akölé"},
    "af": {"name": "Afrikaans", "nativeName": "Afrikaans"},
    "ak": {"name": "Akan", "nativeName": "Akana"},
    "alz": {"name": "Alangan", "nativeName": "Alangan"},
    "am": {"name": "Amharic", "nativeName": "አማርኛ"},
    "ar": {"name": "Arabic", "nativeName": "العربية"},
    "as": {"name": "Assamese", "nativeName": "অসমীয়া"},
    "awa": {"name": "Awadhi", "nativeName": "अवधी"},
    "ay": {"name": "Aymara", "nativeName": "Aymara"},
    "az": {"name": "Azerbaijani", "nativeName": "Azərbaycan dili"},
    "ba": {"name": "Bashkir", "nativeName": "Башҡорт теле"},
    "ban": {"name": "Balinese", "nativeName": "Basa Bali"},
    "bbc": {"name": "Batak Toba", "nativeName": "Bata Toba"},
    "be": {"name": "Belarusian", "nativeName": "Беларуская"},
    "bem": {"name": "Bemba", "nativeName": "Ichibemba"},
    "bew": {"name": "Betawi", "nativeName": "Bahasa Betawi"},
    "bg": {"name": "Bulgarian", "nativeName": "български"},
    "bho": {"name": "Bhojpuri", "nativeName": "भोजपुरी"},
    "bik": {"name": "Bikol", "nativeName": "Bikol"},
    "bm": {"name": "Bambara", "nativeName": "Bamanankan"},
    "bn": {"name": "Bengali", "nativeName": "বাংলা"},
    "br": {"name": "Breton", "nativeName": "Brezhoneg"},
    "bs": {"name": "Bosnian", "nativeName": "Bosanski"},
    "bts": {"name": "Baatonum", "nativeName": "Baatonum"},
    "btx": {"name": "Batu", "nativeName": "Batu"},
    "bua": {"name": "Buriat", "nativeName": "буряад"},
    "ca": {"name": "Catalan", "nativeName": "Català"},
    "ceb": {"name": "Cebuano", "nativeName": "Cebuano"},
    "cgg": {"name": "Chiga", "nativeName": "Rukiga"},
    "chm": {"name": "Mari", "nativeName": "Марий йылме"},
    "ckb": {"name": "Central Kurdish", "nativeName": "کوردیی ناوەندی"},
    "cnh": {"name": "Central Han", "nativeName": "中央汉族语言"},
    "co": {"name": "Corsican", "nativeName": "Corsu"},
    "crh": {"name": "Crimean Tatar", "nativeName": "Qırımtatar tili"},
    "crs": {"name": "Seselwa Creole French", "nativeName": "Kreol Seselwa"},
    "cs": {"name": "Czech", "nativeName": "Čeština"},
    "cv": {"name": "Chuvash", "nativeName": "Чӑваш чӗлхи"},
    "cy": {"name": "Welsh", "nativeName": "Cymraeg"},
    "da": {"name": "Danish", "nativeName": "Dansk"},
    "de": {"name": "German", "nativeName": "Deutsch"},
    "din": {"name": "Dinka", "nativeName": "Thuɔŋjäŋ"},
    "doi": {"name": "Dogri", "nativeName": "डोगरी"},
    "dov": {"name": "Dov", "nativeName": "Dov"},
    "dv": {"name": "Divehi", "nativeName": "ދިވެހި"},
    "dz": {"name": "Dzongkha", "nativeName": "རྫོང་ཁ"},
    "ee": {"name": "Ewe", "nativeName": "Eʋegbe"},
    "el": {"name": "Greek", "nativeName": "Ελληνικά"},
    "en": {"name": "English", "nativeName": "English"},
    "eo": {"name": "Esperanto", "nativeName": "Esperanto"},
    "es": {"name": "Spanish", "nativeName": "Español"},
    "et": {"name": "Estonian", "nativeName": "Eesti"},
    "eu": {"name": "Basque", "nativeName": "Euskara"},
    "fa": {"name": "Persian", "nativeName": "فارسی"},
    "ff": {"name": "Fula", "nativeName": "Fulfulde"},
    "fi": {"name": "Finnish", "nativeName": "Suomi"},
    "fj": {"name": "Fijian", "nativeName": "Vosa Vakaviti"},
    "fr": {"name": "French", "nativeName": "Français"},
    "fy": {"name": "Frisian", "nativeName": "Frysk"},
    "ga": {"name": "Irish", "nativeName": "Gaeilge"},
    "gaa": {"name": "Gã", "nativeName": "Gã"},
    "gd": {"name": "Scottish Gaelic", "nativeName": "Gàidhlig"},
    "gl": {"name": "Galician", "nativeName": "Galego"},
    "gn": {"name": "Guarani", "nativeName": "Ava-Guarani"},
    "gom": {"name": "Goan Konkani", "nativeName": "कोंकणी"},
    "gu": {"name": "Gujarati", "nativeName": "ગુજરાતી"},
    "ha": {"name": "Hausa", "nativeName": "Hausa"},
    "haw": {"name": "Hawaiian", "nativeName": "ʻŌlelo Hawaiʻi"},
    "he": {"name": "Hebrew", "nativeName": "עברית"},
    "hi": {"name": "Hindi", "nativeName": "हिन्दी"},
    "hil": {"name": "Hiligaynon", "nativeName": "Ilonggo"},
    "hmn": {"name": "Hmong", "nativeName": "Hmoob"},
    "hr": {"name": "Croatian", "nativeName": "Hrvatski"},
    "hrx": {"name": "Haryanvi", "nativeName": "हरियाणवी"},
    "ht": {"name": "Haitian", "nativeName": "Kreyòl Ayisyen"},
    "hu": {"name": "Hungarian", "nativeName": "Magyar"},
    "hy": {"name": "Armenian", "nativeName": "Հայերեն"},
    "id": {"name": "Indonesian", "nativeName": "Bahasa Indonesia"},
    "ig": {"name": "Igbo", "nativeName": "Igbo"},
    "ilo": {"name": "Ilokano", "nativeName": "Ilokano"},
    "is": {"name": "Icelandic", "nativeName": "Íslenska"},
    "it": {"name": "Italian", "nativeName": "Italiano"},
    "iw": {"name": "Hebrew (Old)", "nativeName": "עִבְרִית"},
    "ja": {"name": "Japanese", "nativeName": "日本語"},
    "jv": {"name": "Javanese", "nativeName": "ꦧꦱꦗꦮ"},
    "jw": {"name": "Javanese", "nativeName": "ꦧꦱꦗꦮ"},
    "ka": {"name": "Georgian", "nativeName": "ქართული"},
    "kk": {"name": "Kazakh", "nativeName": "Қазақ тілі"},
    "km": {"name": "Khmer", "nativeName": "ខ្មែរ"},
    "kn": {"name": "Kannada", "nativeName": "ಕನ್ನಡ"},
    "ko": {"name": "Korean", "nativeName": "한국어"},
    "kri": {"name": "Krio", "nativeName": "Kriolu"},
    "ktu": {"name": "Kutchi", "nativeName": "કચ્છી"},
    "ku": {"name": "Kurdish", "nativeName": "Kurdî"},
    "ky": {"name": "Kyrgyz", "nativeName": "Кыргызча"},
    "la": {"name": "Latin", "nativeName": "Latina"},
    "lb": {"name": "Luxembourgish", "nativeName": "Lëtzebuergesch"},
    "lg": {"name": "Ganda", "nativeName": "Luganda"},
    "li": {"name": "Limburgish", "nativeName": "Limburgs"},
    "lij": {"name": "Ligurian", "nativeName": "Ligure"},
    "lmo": {"name": "Lombard", "nativeName": "Lombard"},
    "ln": {"name": "Lingala", "nativeName": "Lingála"},
    "lo": {"name": "Lao", "nativeName": "ລາວ"},
    "lt": {"name": "Lithuanian", "nativeName": "Lietuvių"},
    "ltg": {"name": "Latgalian", "nativeName": "Latgaļu"},
    "luo": {"name": "Luo", "nativeName": "Luo"},
    "lus": {"name": "Lushai", "nativeName": "Mizo"},
    "lv": {"name": "Latvian", "nativeName": "Latviešu"},
    "mai": {"name": "Maithili", "nativeName": "मैथिली"},
    "mak": {"name": "Makassarese", "nativeName": "Bahasa Makassar"},
    "mg": {"name": "Malagasy", "nativeName": "Malagasy"},
    "mi": {"name": "Māori", "nativeName": "Māori"},
    "min": {"name": "Minangkabau", "nativeName": "Minangkabau"},
    "mk": {"name": "Macedonian", "nativeName": "Македонски"},
    "ml": {"name": "Malayalam", "nativeName": "മലയാളം"},
  };

  String? getDisplayLanguage(String code) {
    if (isoLangs.containsKey(code)) {
      return isoLangs[code]?["name"];
    } else {
      throw Exception("Language code is incorrect");
    }
  }

  String? getLanguageCode(String name) {
    for (var entry in isoLangs.entries) {
      if (entry.value["name"] == name) {
        return entry.key;
      }
    }
    throw Exception("Language name is incorrect");
  }
}
